sudo: false

language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.4

install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

script:
  - flake8 greeking
  - coverage run setup.py test

after_success:
  - coveralls
